### ISSUE TITLE
Numpy missing in pyproject.toml

### ISSUE THREAD

**Issue by qw-in** [jhnnsrs/turms#1]
Hi, just playing around with the library. Attempting to run `poetry run turms gen` raises at this line:

https://github.com/jhnnsrs/turms/blob/93d1dc19b64acad06beddf538b4043e6f69b48e8/turms/plugins/funcs.py#L6

Assuming it is because poetry is not installing numpy

Edit: not sure if this is because plugins will be installed as dependencies in the future

**Comment by jhnnsrs** [comment]
Hey! Thanks for checking it out.
That numpy import was accidental. Pushed fix to master !
