### ISSUE TITLE
Support for schema from local path

### ISSUE THREAD

**Issue by j-riebe** [jhnnsrs/turms#2]
First of all, this seems like a nice project. 

Would it be hard, to support loading the schema from a bunch of local ``.graphql`` files?

Currently, using a directory path as `projects.default.schema` in graphql.config.yaml isn't allowed.

**Comment by jhnnsrs** [comment]
Just added support: https://github.com/jhnnsrs/turms/commit/335e96f9f1cb0830143d763fd3b62de192b23769
Does this work for you? :)

**Comment by j-riebe** [comment]
Works like a charm 👍

**Comment by j-riebe** [comment]
Hey, I just noticed that your fix only supports a single graphql file.

Could you add support for concatenating multiple graphql-files from a given directory?

The JS graphql-codegen allows paths in the configuration like `/path/**/*.graphql` which scans for all graphql-files in path and all its subdirectories (https://www.graphql-code-generator.com/docs/config-reference/schema-field#local-graphql-files).

Have at look at this ariadne util as a starting point:
https://github.com/mirumee/ariadne/blob/3921fb1d7cd156eb7b5dc39e9a0695508f187cdd/ariadne/load_schema.py#L1-L32

**Comment by jhnnsrs** [comment]
https://github.com/jhnnsrs/turms/commit/8a8f621903d5b9b4958a4eeeed25f3ead604ddcd should now support it!

**Comment by j-riebe** [comment]
Top 👍
