### ISSUE TITLE
__future__.annotations simplifies generating Forward References

### ISSUE THREAD

**Issue by j-riebe** [jhnnsrs/turms#32]
@jhnnsrs why do we even keep track of Forward Reference vs. direct call if we can just add
```python
from __future__ import annotations
```
to the top of the file?

We would still need to call `update_forward_refs()` but the registration process would be just adding the type to a set "blindly".
The annotation could be always generated ast `ast.Name()`.

Example:
```python
from pydantic import BaseModel

class Foo(BaseModel):
    bar: "Bar"

class Bar(BaseModel):
    test: str

Foo.update_forward_refs()
```

vs. 

```python
from __future__ import annotations
from pydantic import BaseModel

class Foo(BaseModel):
    bar: Bar

class Bar(BaseModel):
    test: str

Foo.update_forward_refs()
```

**Comment by jhnnsrs** [comment]
Could definitely get behind this. 

There is however still discussion around the PEP:
https://peps.python.org/pep-0649/
https://peps.python.org/pep-0563/

They would just impact the import though at this point, as there doesn't seem to be that much convergence in the actual replacement of strings. Maybe we could have a config setting like:
use_pep649:  and then import from __future__ import co_annotations
