### ISSUE TITLE
Escape reserved python keywords with alias

### ISSUE THREAD

**Issue by j-riebe** [jhnnsrs/turms#5]
[Keywords](https://realpython.com/lessons/reserved-keywords/) like `from` can't be used as field names.

The [pydantic-graphql-codegen](https://github.com/qw-in/graphql-codegen-pydantic) package does it like this, (but not for all keywords):

GQL
```graphql 
type Foo {
  from: String!
}
```
PY
```python
class Foo(BaseModel)
    from_: str = Field(alias="from")
```

**Comment by jhnnsrs** [comment]
https://github.com/jhnnsrs/turms/commit/1e9743df12785d46e5afb102c2f636dd65891e11 should fix it

**Comment by j-riebe** [comment]
Lightning fast 🚀
