### ISSUE TITLE
Compatibility with Python 3.7 and 3.8

### ISSUE THREAD

**Issue by jhnnsrs** [jhnnsrs/turms#7]
Current build has no compatibiliy with python 3.7 and 3.8 as we are  relying on python 3.9 ast.unparse for generation of code. The current compatibility mode using astunparser fails on pthon 3.7 and python 3.8.

**Comment by j-riebe** [comment]
Additionaly 3.7 doesn't know the walrus operator `:=` which is introduced first in 3.8.

From the test runner
```
turms\run.py:5: in <module>
    from turms.helpers import import_string
E     File "D:\a\turms\turms\turms\helpers.py", line 11
E       (module := sys.modules.get(module_path))
E               ^
E   SyntaxError: invalid syntax
```

**Comment by jhnnsrs** [comment]
This is a monument to why just copy paste from Django source code is not the smartest idea.

**Comment by j-riebe** [comment]
In general, you should be able to separate code generation from code usage (e.g. as GQL-Client).

That would allow you, to put the complete code generation into a Dockerimage* with a single python version (you could mount generated and source files + config as volumes).

The generated code may then be used by other projects with arbitrary python 3.x versions that doesn't even require turms as a dependency. 
For the latter, you'd need to embedd all imported classes into the generated Code itself.

This would make turms a pure dev-dependency, as it should be for a codegen-tool.

*Dockerimage is just an example for an independent project. It could be another venv with the required python version as well.

**Comment by jhnnsrs** [comment]
Completely agreed. I think that should be the set goal. I did just (accidentally) merge a pull request the other day that should address part of the issue : everything should now rely solely on pydantic.BaseModel.

And I love, love docker container idea! Would you be willing to write a PR? 

I also changed the funcs plugin to in theory call any function and pass along additional signature (Addressing  the issue that you don't have to rely on contextvars or global context but can actually pass your gql client). So there is no longer any need for custom query classes as that would happen in the function.  

Also there is now docosaurus website, that should host the documentation at some point. If you have some time, let me know what you think or alter as you wish :D 

Thanks for your contributions!

**Comment by j-riebe** [comment]
Docker should be done pretty fast

It just requires a dockerfile like this:
```Dockerfile
FROM python:3.9-alpine  # small python base image

RUN pip install turms  # maybe fix version to image tag and include optional dependencies

VOLUME /graphql.config.yaml
VOLUME /generated
WORKDIR /

CMD ["turms", "gen"]
```
There are two things to notice here: 
* We need to mount the generated files as a volume, to get them outside of the docker container. 
* The location must match with the configuration. 

It'd also be nice to "bake" a reasonable default config into the dockerimage that can be overriden by file-mounting it with a custom file.
Even better would be an approach via environment variables. 
We could leverage pydantic's BaseSettings for this.
Do you know, if pydantics settings support setting nested values through env vars?

Icing on the cake would be CI (e.g. GitHub Action) + a public docker repo (e.g. dockhub)
