### ISSUE TITLE
[Feature] Generate code in more pythonic snake_case style

### ISSUE THREAD

**Issue by j-riebe** [jhnnsrs/turms#8]
For the wishlist, I'd be very excited if turms could output snake_case code.

I know, you could use a BaseModel with an `alias_generator` to do the job of converting the GraphQL-camelCase to pythons snake_case. Unfortunately most python IDEs won't support code-completition based on this alias-generator.

Additionally, I noticed that class names can be generated in None-PascalCase if the corresponding GraphQL-Type is formatted accordingly.

```type lowerCaseFirstType  --> class lowerCaseFirstType```

The pythonic way, would be to capitalize the first letter, no matter what.
I understand, that this might cause confusion due to discrepancies with the schema or existing projects.

But to generate

> Generate beautifully typed Operations, Enums,... (from Readme)

this (optional) feature would be awesome.

I know, that this might be a lot of work for some syntactic sugar (but: no pain no gain).

**Comment by jhnnsrs** [comment]
WIth the support for stylers that should now be now possible: One can specify (pipeable) rules for the generation of classnames (support for fragment, enum, inputtype, query, mutation, subscription). Also the stylers allow the same for field names (e.g. snakecasing), and will autogenerate an alias field if that field does no longer adhere to the queried alias or node name) :)

Is that a fix? ;)
